### ISSUE TITLE
Is goja-node still being maintained

### ISSUE THREAD

**Issue by uucckk** [dop251/goja_nodejs#10]
Hello, I am the author of airoot-uisys, referring to your project. Goja is a great project.

I want to use "goja-nodejs" to run "uglifyJS",uglifyJS is a nodejs project.

I would like to know whether the goja-nodejs project is mature now and whether it can be supported in the long time。

**Comment by dop251** [comment]
Hi. I am not actively developing it, but will consider merge requests.

**Comment by uucckk** [comment]
Ok, thanks. Goja is really fast.

I wonder if the performance will improve in the next release.
