### ISSUE TITLE
eventloop: Aux jobs sometimes run on stopped loop

### ISSUE THREAD

**Issue by nwidger** [dop251/goja_nodejs#20]
I believe there is a race condition within the eventloop package which in certain conditions causes aux jobs queued via `loop.addAuxJob` to be run after the loop is stopped via `Stop`.

I can fairly reliably reproduce the race with the following test added to `eventloop/eventloop_test.go`:

``` go
func TestRunOnStoppedLoop(t *testing.T) {
	t.Parallel()
	loop := NewEventLoop()
	wg := &sync.WaitGroup{}
	wg.Add(1)
	go func() {
		defer wg.Done()
		for !t.Failed() {
			loop.Start()
			<-time.After(10 * time.Millisecond)
			loop.Stop()
		}
	}()
	wg.Add(1)
	go func() {
		defer wg.Done()
		for !t.Failed() {
			loop.RunOnLoop(func(*goja.Runtime) {
				if !loop.running {
					t.Fatal("running job on stopped loop")
					return
				}
			})
			<-time.After(10 * time.Millisecond)
		}
	}()
	done := make(chan struct{})
	go func() {
		wg.Wait()
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(2 * time.Second):
	}
}
```

With example output looking like:

```
$ go test -run TestRunOnStoppedLoop
--- FAIL: TestRunOnStoppedLoop (0.76s)
    eventloop_test.go:297: running job on stopped loop
FAIL
exit status 1
FAIL	github.com/dop251/goja_nodejs/eventloop	0.766s
```

I believe this happens when the following interleaving of events occurs within a single loop iteration of `loop.run`:

1. The loop.run goroutine runs the job queued by the loop's `Stop` method [here](https://github.com/dop251/goja_nodejs/blob/master/eventloop/eventloop.go#L204), thus setting `loop.running` to `false`.
2. Another goroutine queues the aux job which checks if `loop.running` [here](https://github.com/dop251/goja_nodejs/blob/master/eventloop/eventloop.go#L217).
3. The loop.run goroutine runs the aux job which checks if `loop.running` [here](https://github.com/dop251/goja_nodejs/blob/master/eventloop/eventloop.go#L207).  Since `loop.running` has been set to false in step 1, the test fails.

I'm running the latest `master` for both `goja` and `goja_nodejs`.

**Comment by dop251** [comment]
Thanks for reporting. This was not the only issue though, another one was that `Stop()` was returning too early, after the job ran but before the loop was completed. If a subsequent `Start()` call was quick enough to set the `running` flag before the loop got to the condition check, there would be two instances of loop running in parallel. I have fixed both issues.

**Comment by nwidger** [comment]
Fantastic, thank you for fixing both issues!
