### ISSUE TITLE
setInterval   setImmediate

### ISSUE THREAD

**Issue by cjf621** [dop251/goja_nodejs#66]
setImmediate  if of the nodejs cheak，It has a higher priority，but goja use select，weakup or jobchan  No priority， it is bug？

**Comment by dop251** [comment]
It's not that simple, if you run this:

```js
setTimeout(() => {
    console.log("timeout");
});

setImmediate(() => {
    console.log("immediate");
});

setTimeout(function() {
    setTimeout(function() {
        console.log('setTimeout')
    }, 0);
    setImmediate(function() {
        console.log('setImmediate')
    });
}, 10);
```

You'll consistently get 
```console
timeout
immediate
setImmediate
setTimeout
```
Quick research shows that there is no hard requirement on the ordering, for example this [article](https://nodejs.dev/en/learn/understanding-setimmediate/) says:

> A setTimeout() callback with a 0ms delay is very similar to setImmediate(). The execution order will depend on various factors, but they will be both run in the next iteration of the event loop.

In any case, the node's implementation of event loop is quite complex, and it would be non-trivial to implement something that mimics it precisely. Having said that, I'm always open to consider PRs.

**Comment by cjf621** [comment]
> It's not that simple, if you run this:
> 
> ```js
> setTimeout(() => {
>     console.log("timeout");
> });
> 
> setImmediate(() => {
>     console.log("immediate");
> });
> 
> setTimeout(function() {
>     setTimeout(function() {
>         console.log('setTimeout')
>     }, 0);
>     setImmediate(function() {
>         console.log('setImmediate')
>     });
> }, 10);
> ```
> 
> You'll consistently get
> 
> ```
> timeout
> immediate
> setImmediate
> setTimeout
> ```
> 
> Quick research shows that there is no hard requirement on the ordering, for example this [article](https://nodejs.dev/en/learn/understanding-setimmediate/) says:
> 
> > A setTimeout() callback with a 0ms delay is very similar to setImmediate(). The execution order will depend on various factors, but they will be both run in the next iteration of the event loop.
> 
> In any case, the node's implementation of event loop is quite complex, and it would be non-trivial to implement something that mimics it precisely. Having said that, I'm always open to consider PRs.

This example it is  settimeout block，So it's expected output，but if i have many long time script is run，i can not use setImmediate or other api Insert Before Queue

**Comment by dop251** [comment]
As I said, PRs are welcome.
