### ISSUE TITLE
Use ada-url for url implementation

### ISSUE THREAD

**Issue by mkadirtan** [dop251/goja_nodejs#79]
This package doesn't use the Go url parser directly, because Go and Node.js follow different standards for URL parsing. However, the new ada URL parser for Node.js has Go bindings, are you open to using it in this project? If so, I can do the work, just let me know.

**Comment by dop251** [comment]
I would like to keep this project pure Go, without cgo dependencies. You can, however, create a separate project and use the module it provides instead of the default one.
