### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PaluMacil** [dop251/goja_nodejs#8]
goja#76 is related to this issue. I'd like to start contributing some important node libraries just as functionality from fs, path, etc. I noticed you haven't answered the Windows filepath issue PR, so before I made a PR for a roadmap / priority list, I wanted to first make sure you are still interested in maintaining this library at least as far as accepting PRs goes. I am interested in doing some work but lack the experience you have.

On a somewhat related note, I would like to start a goja_browser project which has dom functionality. If you are interested in accepting PRs, I think you are more qualified to own the repo.

**Comment by tooolbox** [comment]
@dop251 Any thoughts on this?

**Comment by dop251** [comment]
I cannot spend too much time on this project but I will do my best to review PRs. I've just enabled CI which should help to speed this up a bit.
